oc_core:
    resource: "@CoreBundle/Controller/CoreController.php"
    type: annotation
    prefix: /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform