<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        // Méthode 1: en passant par l'Entity Manager
        $querybuilder = $this->_em->createQueryBuilder()
                                  ->select('a')
                                  ->from($this->_entityName, 'a');

        /* Dans un repository, $this->_entityName est le namespace de l'entité gérée
           Ici, il vaut donc OC\PlatformBundle\Entity\Advert
        */

        // Méthode 2: en passant par le raccourci (recommandé)
        $queryBuilder2 = $this->createQueryBuilder('a');

        /* On n'ajoute pas de critère ou de tri particulier, la construction
           de notre requête est finie. 
        */

        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder2->getQuery();

        // On récupère les résultats à partir de la Query
        $results = $query->getResult();

        // On retourne les résultats
        return $results;

        /* Version raccourcie

            $this->createQueryBuilder('a')
                 ->getQuery()
                 ->getResult();
        */
    }

    public function myFindOne($id)
    {
        $querybuilder = $this->createQueryBuilder('a');

        $querybuilder->where('a.id = :id')->setParameter('id', $id);

        return $querybuilder->getQuery()->getResult();
    }

    public function findByAuthorAndDate($author, $date)
    {
        $querybuilder = $this->createQueryBuilder('a');

        $querybuilder->where('a.author = :author')
                     ->setParameter('author', $author)
                     ->andWhere('a.date < :year')
                     ->setParameter('year', $year)
                     ->orderBy('a.date', 'DESC');

        return $querybuilder->getQuery()->getResult();
    }

    public function whereCurrentYear(QueryBuilder $qb)
    {
        $qb->andWhere('a.date BETWEEN :start AND :end')
           ->setParameter('start', new \Datetime(date('Y').'-01-01'))
           ->setParameter('end', new \Datetime(date('Y').'-12-31'));
    }
}
